# Generated by Django 5.2.15 on 2026-07-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorizationPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Authorization Permission",
                "verbose_name_plural": "Authorization Permissions",
                "default_permissions": (),
            },
        ),
    ]
