# Generated by Django 5.2.15 on 2026-07-09 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_is_email_verified_emailverificationtoken"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailverificationtoken",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Email Verification Token",
                "verbose_name_plural": "Email Verification Tokens",
            },
        ),
    ]
