# Generated by Django 5.2.15 on 2026-07-10 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domains", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TLD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "extension",
                    models.CharField(
                        help_text="Example: com, org, net, co.ke",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("supports_dnssec", models.BooleanField(default=False)),
                ("supports_idn", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Top-Level Domain",
                "verbose_name_plural": "Top-Level Domains",
                "ordering": ["extension"],
            },
        ),
        migrations.AddField(
            model_name="domain",
            name="tld",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="domains",
                to="domains.tld",
            ),
        ),
    ]
