# Generated by Django 5.2.15 on 2026-07-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domains", "0002_tld_domain_tld"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tld",
            options={"ordering": ("registration_order", "extension")},
        ),
        migrations.AddField(
            model_name="tld",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tld",
            name="registration_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="tld",
            name="extension",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
