# Generated by Django 5.2.15 on 2026-07-11 03:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domains", "0003_alter_tld_options_tld_is_featured_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DomainPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_type",
                    models.CharField(
                        choices=[
                            ("register", "Registration"),
                            ("renew", "Renewal"),
                            ("transfer", "Transfer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("years", models.PositiveSmallIntegerField()),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "registrar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="domains.registrar",
                    ),
                ),
                (
                    "tld",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="domains.tld",
                    ),
                ),
            ],
            options={
                "ordering": ("tld", "price_type", "years"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("registrar", "tld", "price_type", "years"),
                        name="unique_domain_price",
                    )
                ],
            },
        ),
    ]
